---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -s .
  flake8 .
platforms:
  - name: instance
    image: '${MOLECULE_DISTRO:-krakerdev/opensuse-ansible}'
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
